config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'home#index'
    get 'welcome', to: 'home#index'

    # Users controller routes
    get 'sign_up', to: 'users#new'
    post 'sign_up', to: 'users#create'

    # Sessions controller routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resource :user, only: %i[edit update]

    # Steps controller routes
    resources :steps, only: %i[show update edit] do
      collection do
        get 'check_your_answers', to: 'steps#check_your_answers'
        get 'results', to: 'steps#results'
        get 'scoreboard', to: 'steps#scoreboard'
        get 'stop', to: 'steps#check_your_answers'
        get 'download', to: 'steps#download'
      end
    end

    # Stopwatch controller routes
    get 'stopwatch/start', to: 'stopwatch#start'

  end

  # Catch-all route for handling 404 Not Found
  match '*path', to: 'application#render_404', via: :all
end

app/models/user.rb
# User represents a registered user of the application.
#
# It includes functionalities for authentication and associations with answers
# submitted in quizzes.
#
# Attributes:
#   - email: Must be present, formatted as a valid email address, and unique across users.
#   - username: Must be present, serving as the unique identifier for the user.
#
# Associations:
#   - has_many :answers: Represents the answers submitted by the user in quizzes.
#     These answers are dependent on the user and will be destroyed if the user is deleted.
#
# Validations:
#   - email: Presence and format validation using URI::MailTo::EMAIL_REGEXP, ensuring uniqueness.
#   - username: Presence validation, ensuring each user has a username.
#
# Security:
#   - has_secure_password: Provides password encryption and validation capabilities.
#
# Note: User models are crucial for managing user authentication and tracking user activities
#       such as quiz participation and results.
class User < ApplicationRecord
  has_secure_password
  has_many :answers, dependent: :destroy

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :username, presence: true
end

app/controllers/users_controller.rb
# UsersController manages user-related actions such as registration, editing profile, and updating user information.
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]
  before_action :redirect_if_authenticated, only: %i[create new]
  # GET /users/new
  # Displays the user registration form.
  def new
    @user = User.new
  end
  # GET /users/edit
  # Displays the user profile edit form.
  def edit
    # Memoized variable for current_user's top score.
    @edit ||= Answer.
              where(completed: true).
              where(user: current_user).
              where.not(score: nil).
              order(score: :desc).
              first&.
              score || I18n.t('users.no_score_available')
  end
  # POST /users
  # Creates a new user based on the submitted parameters.
  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      session[:current_user_id] = @user.id
      redirect_to welcome_path(locale: I18n.locale), notice: I18n.t('users.signed_up')
    else
      render :new, status: :unprocessable_content
    end
  end
  # PATCH /users
  # Updates the current user's profile based on the submitted parameters.
  def update
    if current_user.update(user_update_params)
      redirect_to edit_user_path(locale: current_user.language), notice: I18n.t('users.updated')
    else
      render :edit, status: :unprocessable_content, locale: I18n.locale
    end
  end
  private
  # Strong parameters for user creation.
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  # Strong parameters for user update.
  def user_update_params
    params.require(:user).permit(:username, :language)
  end
end

app/views/users/edit.html.erb
<% provide(:title, t('forms.edit_profile')) %>

<div class="container mt-5">
  <h2 class="text-danger"><%= t('forms.edit_profile') %></h2>
  <hr class="border-top border-3 border-danger my-2">
  <br/>
  <%= form_with(model: current_user, url: user_path, local: true, method: :patch) do |form| %>
    <%= render partial: "shared/form_errors", locals: { object: form.object } %>

    <div class="mb-3">
      <%= form.label :username, t('forms.username'), class: "form-label" %>
      <%= form.text_field :username, class: "form-control border-danger" %>
    </div>

    <div class="mb-3">
      <%= form.label :email, t('forms.email'), class: "form-label" %>
      <%= form.text_field :email, class: "form-control border-danger", disabled: true %>
    </div>

    <div class="mb-3">
      <%= form.label :language, t('forms.language'), class: "form-label" %>
      <%= form.select :language, I18n.available_locales.map { |locale| [I18n.t("languages.#{locale}"), locale] }, {}, class: "form-select" %>
    </div>

    <div class="mb-3">
      <div class="form-control-plaintext"><%= "#{t('forms.top_score_profile')} #{@edit }" %>%</div>
    </div>

    <div class="d-flex justify-content-start">
      <%= form.submit t('forms.update_profile'), class: "btn btn-danger px-5 me-2" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="d-flex align-items-center h-100">
  <div class="row col-12 justify-content-center mt-5 pt-5">
    <div class="col-md-5 col-12 border-end border-2 border-danger p-0 mobile-margin" id="mobile-border">
      <h2 class="text-center"><%= t('users.sign_up_headline') %></h2>
      <h4 class="text-center fw-normal mt-3"><%= t('users.sign_up_line_one') %></h4>
      <%= image_tag 'sign-up-welcome.svg', skip_pipeline: false, alt: "Sign up welcome image" %>
    </div>
    <div class="col-md-4 col-12 ms-5">
      <h2 class="text-center text-light"><%= t('users.create_account') %></h2>
      <div class="mt-5">
        <%= form_with model: @user, url: sign_up_path, html: { class: "signup-form" } do |form| %>
          <%= render partial: "shared/form_errors", locals: { object: form.object } %>
          <%= form.label :username, class: "form-label mt-3" %>
          <%= form.text_field :username, class: "form-control border-danger input-size", required: true %>
          <%= form.label :email, class: "form-label mt-3" %>
          <%= form.email_field :email, class: "form-control border-danger input-size", required: true %>
          <%= form.label :password, class: "form-label mt-3" %>
          <%= form.password_field :password, class: "form-control border-danger input-size", required: true %>
          <%= form.label :password_confirmation, class: "form-label mt-3" %>
          <%= form.password_field :password_confirmation, class: "form-control border-danger input-size", required: true %>
          <div class="text-center text-light">
            <%= form.submit t('forms.sign_up'), class: "btn btn-danger mt-5 w-75" %>
          </div>
        <% end %>
        <div class="d-flex align-items-center justify-content-center mt-3">
          <h5 class="text-center text-light fw-normal pe-1"><%= t('users.login_prompt') %></h5>
          <%= link_to login_path do %>
            <h5 class="text-center text-light fw-semibold text-danger"><%= t('forms.sign_in') %></h5>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>