config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'home#index'
    get 'welcome', to: 'home#index'

    # Users controller routes
    get 'sign_up', to: 'users#new'
    post 'sign_up', to: 'users#create'

    # Sessions controller routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resource :user, only: %i[edit update]

    # Steps controller routes
    resources :steps, only: %i[show update edit] do
      collection do
        get 'check_your_answers', to: 'steps#check_your_answers'
        get 'results', to: 'steps#results'
        get 'scoreboard', to: 'steps#scoreboard'
        get 'stop', to: 'steps#check_your_answers'
        get 'download', to: 'steps#download'
      end
    end

    # Stopwatch controller routes
    get 'stopwatch/start', to: 'stopwatch#start'

  end

  # Catch-all route for handling 404 Not Found
  match '*path', to: 'application#render_404', via: :all
end

app/views/shared/_flag.html.erb
<div class="ms-3">
  <% if I18n.locale == :en %>
    <%= image_tag('en.png', alt: 'English', class: 'rounded-circle', style: 'width:24px') %>
  <% elsif I18n.locale == :fr %>
    <%= image_tag('fr.png', alt: 'French', class: 'rounded-circle', style: 'width:14px') %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2022 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
  </footer>
</div>

app/views/shared/_form_errors.html.erb
<% if object&.errors&.any? %>
  <% if defined?(error_style) && error_style == :quiz %>
    <div class="errors pt-5">
      <h3>Validation errors:</h3>
      <ul class="list-unstyled">
        <% object.errors.each_with_index do |error, _index| %>
          <li>
            <%= link_to validation_error_text(object.current_step, error.attribute[-1]), "#question_#{error.attribute[-1]}", class: "link-danger" %>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <ul class="list-unstyled">
      <% object.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="h-auto navbar bg-danger navbar-quizapp position-sticky">
  <div class="container d-flex align-items-center justify-content-between">
    <div class="d-flex align-items-center">
      <%= link_to welcome_path, class: 'navbar-logo' do %>
        <%logo_html.html_safe %>
      <% end %>
    </div>
    <% if current_user %>
      <div class="d-flex align-items-center">
        <h1 class="h5 me-3 mb-0">
          <%= link_to t('forms.scoreboard'), scoreboard_steps_path, class: 'text-white m-0 fw-normal' %>
        </h1>
        <h1 class="h5 me-3 mb-0">
          <%= link_to t('forms.edit_profile'), edit_user_path, class: 'text-white m-0 fw-normal' %>
        </h1>
        <h1 class="h5 mb-0">
          <%= link_to t('forms.sign_out'), '#', class: 'text-white m-0 fw-normal', data: { bs_toggle: 'modal', bs_target: '#signoutModal' } %>
        </h1>
        <div class="ms-3">
        <% if I18n.locale == :en %>
        <img alt="English" class="rounded-circle" style="width:24px" src="/assets/en-dd5886d2fe8221b32c59aec4ea0d35e99ca4106e948d8eeb415248d988a07954.png">
      <% else %>
        <img alt="French" class="rounded-circle" style="width:24px" src="/assets/fr-325a69cd56fad37707af742198324741e86d1396cfc47ac4fb3e2d39e1306f32.png">
      <% end %>
        </div>
    <% end %>
  </div>
</nav>

app/views/shared/_signout_modal.html.erb
<% if current_user %>
  <div class="modal fade" id="signoutModal" tabindex="-1" aria-labelledby="signoutModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header border-0">
          <h3 class="modal-title" id="signoutModalLabel"><%= t('sessions.sign_out_modal_title') %></h3>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <hr class="m-0 text-danger">
        <div class="modal-body">
          <p><%= t('sessions.sign_out_confirmation') %></p>
        </div>
        <div class="modal-footer justify-content-between border-0">
          <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal"><%= t('sessions.sign_out_cancel') %></button>
          <%= link_to t('forms.sign_out'), "/logout", method: :delete, class: "btn btn-danger", data: { turbo_method: :delete } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_submit_modal.html.erb
<div class="modal fade" id="submitModal" tabindex="-1" aria-labelledby="submitModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header border-0">
        <h3 class="modal-title" id="submitModalLabel"><%= t('check_answers.submit_modal_title') %></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <hr class="m-0 text-danger">
      <div class="modal-body">
        <p><%= t('check_answers.submit_modal_confirmation') %></p>
      </div>
      <div class="modal-footer justify-content-between border-0">
        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal"><%= t('check_answers.submit_modal_cancel') %></button>
         <%= link_to "Submit", "/steps/results", method: :get, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>