config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'home#index'
    get 'welcome', to: 'home#index'

    # Users controller routes
    get 'sign_up', to: 'users#new'
    post 'sign_up', to: 'users#create'

    # Sessions controller routes
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resource :user, only: %i[edit update]

    # Steps controller routes
    resources :steps, only: %i[show update edit] do
      collection do
        get 'check_your_answers', to: 'steps#check_your_answers'
        get 'results', to: 'steps#results'
        get 'scoreboard', to: 'steps#scoreboard'
        get 'stop', to: 'steps#check_your_answers'
        get 'download', to: 'steps#download'
      end
    end

    # Stopwatch controller routes
    get 'stopwatch/start', to: 'stopwatch#start'

  end

  # Catch-all route for handling 404 Not Found
  match '*path', to: 'application#render_404', via: :all
end

app/controllers/steps_controller.rb
# StepsController manages the flow of steps in a quiz application,
# including viewing, editing, updating, and finalizing quiz forms.
class StepsController < ApplicationController
  include Authentication
  include QuizConstantsHelper
  include QuizResultsHelper
  include StepsConcern
  include StepsHelper
  include ScoreboardHelper
  include QuizFormHandler

  before_action :authenticate_user!
  before_action :validate_step, only: %i[show edit update]
  before_action :set_quiz_form, only: %i[show update]

  # GET /steps/:id
  # Displays the quiz form for the specified step.
  def start_timer
    session[:start_time] = Time.now.to_f
    session[:running] = true
    puts plain: "Stopwatch started!"
  end

  def show
    if params[:encoded_params].present?
      @quiz_form = QuizForm.new(decoded_params.permit(:current_step, quiz_results: []))
      @quiz_form.current_user_id = current_user.id
    else
      @quiz_form = QuizForm.new(current_step: params[:id].to_i, current_user_id: current_user.id)
    end

    if @quiz_form.current_step == 1
      start_timer

    end

    restore_quiz_form_state
  end

  # GET /steps/:id/edit
  # Displays the quiz form for editing the specified step.
  def edit
    reset_user_completion_status
    build_quiz_form_with_answers
    restore_quiz_form_state
  end

  # PATCH /steps/:id
  # Updates the quiz form for the specified step.
  def update
    if @quiz_form.valid?
      @quiz_form.update_answers

      # Save current state in session
      session[:quiz_forms] ||= []
      session[:quiz_forms][@quiz_form.current_step - 1] = @quiz_form.attributes

      next_step
    else
      render :show, status: :unprocessable_content
    end
  end

  # GET /check_your_answers
  # Displays the user's completed quiz for review.
  def check_your_answers
    puts "running check_your_answers"
    if session[:start_time] && session[:running]
      elapsed_time = Time.now.to_f - session[:start_time]
      @elapsed_time = elapsed_time.round(2)
      
      if current_user.answers.last
        current_user.answers.last.update(Time: @elapsed_time)
      else
        Answer.create(user: current_user, Time: @elapsed_time)
      end
  
      session[:start_time] = nil
      session[:running] = false
      puts "Elapsed time: #{elapsed_time.round(2)} seconds"
    else
      puts "Stopwatch has not been started yet!"
    end
  
    @quiz_results = current_user.answers.last
    clean_and_complete_quiz
    render :check_your_answers
  end

  # GET /results
  # Displays the user's quiz results.
  def results
    clean_and_complete_quiz
    @quiz_results = current_user.answers.last
    @questions_per_page = QUESTIONS_PER_PAGE
    @score_percentage, @correct_answers, @total_questions = scoring_metrics(@quiz_results)
    @quiz_results.update(score: @score_percentage)

    clear_quiz_form_session_data # <- Clear the quiz form session data

    render :results
  end

  # GET /scoreboard
  # Displays the top scores of completed quizzes.
  # Allows download of scoreboard as CSV.
  def scoreboard
    @top_scores = Answer.where(completed: true).where.not(score: nil).includes(:user).order(score: :desc).limit(10)
    respond_to do |format|
      format.html
      format.csv { send_data generate_csvs(@top_scores), filename: 'top_scores.csv' }
    end
  end

  # GET /download/:id
  # Allows download of an individual quiz result as CSV.
  def download
    @answer = Answer.find(params[:id])
    respond_to do |format|
      format.csv { send_data generate_single_csv(@answer), filename: "quiz_#{@answer.id}_results.csv" }
    end
  end

  private

  # Sets the quiz form based on parameters or defaults.
  def set_quiz_form
    @quiz_form = if params[:quiz_form].present?
                   build_quiz_form_from_params(quiz_form_params)
                 elsif params[:encoded_params].present?
                   build_quiz_form_from_encoded_params
                 else
                   build_default_quiz_form
                 end
  end

  # Restores the state of the quiz form from session storage.
  def restore_quiz_form_state
    saved_state = session[:quiz_forms] && session[:quiz_forms][@quiz_form.current_step - 1]
    @quiz_form.assign_attributes(saved_state) if saved_state
  end

  # Validates that the requested step is within the expected range.
  def validate_step
    render file: Rails.public_path.join('404.html'), status: :not_found unless (1..3).cover?(params[:id].to_i)
  end

  # Marks the current user's quiz as completed and cleans up unfinished attempts.
  def clean_and_complete_quiz
    current_user.answers.last.update(completed: true)
    current_user.answers.where(completed: false).destroy_all
  end
end

app/helpers/steps_helper.rb
# StepsHelper provides helper methods for formatting and managing quiz steps.
#
module StepsHelper
  include QuizConstantsHelper

  # Formats the question to display its page number.
  #
  # Parameters:
  # - question: String representing the question identifier.
  #
  # Returns:
  # - String formatted as "Page X", where X is the page number extracted from the question.
  #
  def format_question(question)
    page_number = question.match(/(\d+)/)[0]
    "Page #{page_number}"
  end

  # Formats the quiz question text based on its internationalization key and index.
  #
  # Parameters:
  # - question: String representing the question identifier.
  # - index: Integer representing the question index within the page.
  #
  # Returns:
  # - String containing the formatted quiz question text.
  #
  def format_quiz_question(question, index)
    I18n.t("quiz_form.#{question}.question_#{index + 1}.question")
  end

  # Calculates the continuous index of a question across multiple quiz pages.
  #
  # Parameters:
  # - current_step: Current step or page number of the quiz.
  # - question_index: Index of the question within its current page.
  #
  # Returns:
  # - Integer representing the continuous index of the question.
  #
  def continuous_index(current_step, question_index)
    ((current_step.to_i - 1) * QUESTIONS_PER_PAGE) + question_index.to_i
  end

  # Generates validation error text for a specific question based on its index.
  #
  # Parameters:
  # - current_step: Current step or page number of the quiz.
  # - question_index: Index of the question within its current page.
  #
  # Returns:
  # - String containing the formatted validation error message.
  #
  def validation_error_text(current_step, question_index)
    "Question #{continuous_index(current_step, question_index)} : #{I18n.t('quiz_form.errors.blank_answer')}"
  end
end

app/views/steps/_choice_questions.html.erb
<% @quiz_form.current_question_range.each do |_key, value| %>
  <% question_index += 1 %>
  <div class="pt-5" id="question_<%= question_index %>">
    <p><strong><%= continuous_index(@quiz_form.current_step, question_index) %>. <%= value[:question] %></strong></p>
  </div>
  <div class="row">
    <%= form.hidden_field :current_step  %>
    <div class="col-lg-6">
    <div class="d-flex align-items-center pt-3">
    <%= form.radio_button "answer_#{question_index}", value[:answer_1], id: "answer_#{question_index}_1", class: "me-2" %>
    <label for="answer_<%= question_index %>_1"><%= value[:answer_1] %></label>
  </div>
      <div class="d-flex align-items-center pt-3">
        <%= form.radio_button "answer_#{question_index}", value[:answer_2], id: "answer_#{question_index}_2", class: "me-2" %>
        <label for="answer_<%= question_index %>_2"><%= value[:answer_2] %></label>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="d-flex align-items-center pt-3">
        <%= form.radio_button "answer_#{question_index}", value[:answer_3], id: "answer_#{question_index}_3", class: "me-2" %>
        <label for="answer_<%= question_index %>_3"><%= value[:answer_3] %></label>
      </div>
      <div class="d-flex align-items-center pt-3">
        <%= form.radio_button "answer_#{question_index}", value[:answer_4], id: "answer_#{question_index}_4", class: "me-2" %>
        <label for="answer_<%= question_index %>_4"><%= value[:answer_4] %></label>
      </div>
    </div>
  </div>
<% end %>

app/views/steps/_free_questions.html.erb
<% @quiz_form.current_question_range.each do |_key, value| %>
  <% question_index += 1 %>
  <div class="pt-5" id="question_<%= question_index %>">
    <p><strong><%= continuous_index(@quiz_form.current_step, question_index) %>. <%= value[:question] %></strong></p>
  </div>
  <div class="row pt-3">
    <%= form.hidden_field :current_step  %>
    <div>
      <%= form.text_field "answer_#{question_index}", class: "form-control border-danger py-2" %>
    </div>
  </div>
<% end %>

app/views/steps/_show.html.erb
<% provide(:title, "Page #{@quiz_form.current_step} of #{QuizConstantsHelper::NUMBER_OF_PAGES}") %>
<div class="container w-75 mt-5 mb-4 pt-5">
  <h2><%= @quiz_form.current_page_range %></h2>
  <hr class="border border-danger w-100 border-2 my-2">
  <% question_index = 0 %>

  <%= form_for @quiz_form, url: step_path(@quiz_form.current_step, locale: I18n.locale), method: :patch do |f| %>
    <%= render partial: "shared/form_errors", locals: { object: @quiz_form, error_style: :quiz } %>

    <% if @quiz_form.current_step < 3 %>
      <%= render "choice_questions", quiz_form: @quiz_form, question_index: question_index, form: f %>
    <% else %>
      <%= render "free_questions", quiz_form: @quiz_form, question_index: question_index, form: f %>
    <% end %>

    <div class="row mt-4">
      <div class="col-12 col-md-6 d-flex justify-content-md-start justify-content-center mb-3 mb-md-0 <%= 'invisible' if @quiz_form.current_step == 1 %>">
        <%= link_to t('forms.back_button'), step_path(@quiz_form.previous_step, locale: I18n.locale), class: "btn btn-outline-danger px-5" %>
      </div>

      <div class="col-12 col-md-6 d-flex justify-content-md-end justify-content-center">
        <% if @quiz_form.current_step < @quiz_form.total_steps %>
          <%= f.submit t('forms.next'), class: "btn btn-danger px-5" %>
        <% else %>
          <%= f.submit t('forms.submit'), class: "btn btn-danger px-5" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/steps/check_your_answers.html.erb
<% provide(:title, t('check_answers.title')) %>
<div id="check-answers" class="container d-flex flex-column align-items-center mt-4 mb-4 pt-5">
  <h1 class="text-danger text-center"><%= t('check_answers.heading') %></h1>
  <hr class="border border-danger w-100 border-2 my-2">
  <p class="text-center">
    <%= "Well done, #{current_user.username}! It took you #{@elapsed_time} seconds" %>
  </p>

  <div class="border border-danger border-bottom-0 rounded overflow-hidden mt-4 w-100">
    <div class="table-responsive">
      <table class="table border-danger m-0">
        <tbody class="table-group-divider border-danger">
          <% question_page_number = 0 %>
          <thead>
            <tr>
              <th scope="col"><%= t('check_answers.table.number') %></th>
              <th scope="col"><%= t('check_answers.table.question') %></th>
              <th scope="col"><%= t('check_answers.table.answer') %></th>
              <th scope="col"><%= t('check_answers.table.change') %></th>
            </tr>
          </thead>
          <% @quiz_results.answer.each do |question, answers| %>
            <% question_page_number += 1 %>
            <% answers.each_with_index do |answer, index| %>
              <tr>
                <td><%= continuous_index(question_page_number, index+1) %></td>
                <td><%= format_quiz_question(question, index) %></td>
                <td><%= answer %></td>
                <td class="text-center">
                  <%= link_to t('check_answers.table.change'), edit_step_path(id: question_page_number, answer: @quiz_results.answer), class: "btn btn-danger px-3" %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to t('check_answers.buttons.submit'), "#", class: "mt-5 btn btn-danger btn-md mx-auto px-5", data: { bs_toggle: "modal", bs_target: "#submitModal" } %>
</div>

<%= render 'shared/submit_modal' %>

app/views/steps/edit.html.erb
<%= render "show", quiz_form: @quiz_form %>

app/views/steps/results.html.erb
<% provide(:title, t('results.title')) %>
<div id="results-page" class="container d-flex flex-column align-items-center mt-4 mb-4 pt-5">
  <h1 class="text-danger text-center"><%= t('results.heading') %></h1>
  <hr class="border border-danger w-100 border-2 my-2">

  <div class="border border-danger w-100 rounded mt-4 mb-4 px-1">
    <h2 class="text-danger text-center mx-3 mt-3">
      <%= t('quiz_results.your_score') %><span class="text-dark"><%= t('quiz_results.score', score: @score_percentage) %></span>
    </h2>
    <h3 class="text-dark text-center mb-3">
      <%= t('quiz_results.questions_correctly_answered', correct: @correct_answers, total: @total_questions) %>
    </h3>
  </div>

  <div class="border border-danger border-bottom-0 rounded overflow-hidden mt-4 mb-4 w-100">
    <div class="table-responsive">
      <table class="table border-danger m-0">
        <thead>
          <tr>
            <th><%= t('results.table.question') %></th>
            <th><%= t('results.table.correct_answer') %></th>
            <th><%= t('results.table.answered') %></th>
            <th><%= t('results.table.correct_incorrect') %></th>
          </tr>
        </thead>
        <tbody class="table-group-divider border-danger">
            <% @quiz_results.answer.each_with_index do |answers, index| %>
              <% answers[1].each_with_index do |_answer, question_index| %>
                <%= generate_table_row(index, question_index, answers) %>
              <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to t('results.buttons.continue'), scoreboard_steps_path, class: "btn btn-danger btn-md mx-auto px-5" %>
</div>

app/views/steps/scoreboard.html.erb
<% provide(:title, t('scoreboard.title')) %>
<div id="check-answers" class="container flex-column align-items-center mt-4 mb-4 pt-5">
  <h1 class="text-danger text-center"><%= t('scoreboard.heading') %></h1>
  <hr class="border border-danger w-100 border-2 my-2">

  <table class="table mt-4">
    <tbody class="table-group-divider border-danger">
      <% @top_scores.each_with_index do |answer, _index| %>
        <thead>
          <tr>
          <% if _index == 0 %>
            <th scope="col"><%= t('scoreboard.table.quiz') %></th>
            <th scope="col"><%= t('scoreboard.table.username') %></th>
            <th scope="col"><%= t('scoreboard.table.date_attempted') %></th>
            <th scope="col"><%= t('scoreboard.table.score') %></th>
            <th scope="col"><%= "Time" %></th>
            <th scope="col"><%= t('scoreboard.table.download') %></th>
          <% end %>
            
        <tr>
          <td>
            <%= t('scoreboard.table.quiz_number', id: answer.id) %>
          </td>
          <td>
            <%= answer.user.username.humanize  %>
          </td>
          <td>
            <%= answer.date_attempted.strftime('%B %d, %Y') %>
          </td>
          <td>
            <%= answer.score %>%
          </td>
          <td>
            <%= answer.Time %>
          </td>
          <td>
            <%= link_to download_steps_path(format: :csv, id: answer.id), class: 'link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-25-hover d-flex align-items-center' do %>
              <i class="bi bi-arrow-down-circle-fill me-2"></i> <%= t('scoreboard.table.download_filename', id: answer.id) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<div id="check-answers" class="container w-75">
  <div class="d-flex flex-column flex-sm-row justify-content-between">
    <%= link_to step_path(id: 1), class: "btn btn-outline-danger btn-md mb-2 mb-md-0" do %>
      <i class="bi bi-play-circle me-2"></i> <%= t('scoreboard.buttons.start_new_quiz') %>
    <% end %>

    <%= link_to scoreboard_steps_path(format: :csv), class: 'btn btn-danger btn-md mb-2 mb-md-0' do %>
      <i class="bi bi-arrow-down-circle-fill me-2"></i> <%= t('scoreboard.buttons.download_all_results') %>
    <% end %>
  </div>
</div>

app/views/steps/show.html.erb
<%= render "show", quiz_form: @quiz_form %>